spring.application.name=smartShoppingApp

spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp


# MYSQL DATABASE CONFIGURATION
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# If running on the cloud, it will use the variables (DB_URL, etc). 
# If running locally, it defaults to your local database settings.
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/shoppingAPP?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Karansri@6423}


#HIBERNATE / JPA CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
